
swagger: "2.0"
info:
  title: "Argent Bank - Transactions API"
  description: "Final Swagger proposal based on feedback and wireframe"
  version: "1.0.0"
host: "localhost:3001"
basePath: "/api/v1"
schemes:
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Get all transactions for current month
      description: Returns a list of transactions grouped by account
      parameters:
        - name: accountId
          in: query
          type: string
          required: false
          description: Optional account ID to filter transactions
      responses:
        "200":
          description: List of transactions
          schema:
            type: array
            items:
              $ref: "#/definitions/TransactionSummary"
        "401":
          description: Unauthorized
        "500":
          description: Server error

  /transaction/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Get a specific transaction
      description: Returns full transaction detail
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Transaction details
          schema:
            $ref: "#/definitions/Transaction"
        "404":
          description: Transaction not found
        "401":
          description: Unauthorized

    put:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Update a transaction's category or notes
      description: Allows modification of editable fields only (category, notes)
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - in: body
          name: transaction
          required: true
          schema:
            $ref: "#/definitions/TransactionUpdate"
      responses:
        "200":
          description: Transaction updated
        "400":
          description: Invalid input
        "404":
          description: Transaction not found
        "401":
          description: Unauthorized

definitions:
  TransactionSummary:
    type: object
    properties:
      date:
        type: string
        format: date
        example: "2020-06-20"
      description:
        type: string
        example: "Golden Sun Bakery"
      amount:
        type: number
        format: float
        example: 50.00
      balance:
        type: number
        format: float
        example: 2187.79

  Transaction:
    type: object
    properties:
      id:
        type: string
        example: "txn_123456789"
      accountId:
        type: string
        example: "acc_987654321"
      date:
        type: string
        format: date
        example: "2020-06-20"
      description:
        type: string
        example: "Golden Sun Bakery"
      amount:
        type: number
        format: float
        example: 50.00
      balance:
        type: number
        format: float
        example: 2187.79

  TransactionUpdate:
    type: object
    properties:
      id:
        type: string
        example: "txn_123456789"
      accountId:
        type: string
        example: "acc_987654321"
      date:
        type: string
        format: date
        example: "2020-06-20"
      description:
        type: string
        example: "Golden Sun Bakery"
      amount:
        type: number
        format: float
        example: 50.00
      balance:
        type: number
        format: float
        example: 2187.79
      transactionType:
        type: string
        enum: [Electronic, Wire, Check]
        example: "Electronic"
      category:
        type: string
        enum: [Food, Transport, Health, Shopping, Utilities, Rent, Travel]
        example: "Food"
      notes:
        type: string
        example: "Lunch with client"